{% set version = "1.18.0" %}


package:
  name: osmium-tool
  version: {{ version }}


source:
  - url: https://github.com/osmcode/osmium-tool/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 5438f57043c9df05137ca4bd1b1e4a5fb1c9c8c49cb4bec43a5f1ef30ed68fb5
    folder: osmium-tool

  - url: https://github.com/osmcode/libosmium/archive/refs/tags/v2.21.0.tar.gz
    sha256: 5a222e555865f742102d2802a7ad7ef91d6e1c8944c097c70a924214e079c858
    folder: libosmium

  - url: https://github.com/mapbox/protozero/archive/refs/tags/v1.8.0.tar.gz
    sha256: d95ca543fc42bd22b8c4bce1e6d691ce1711eda4b4910f7863449e6517fade6b
    folder: protozero


build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

  host:
    - libboost-devel
    - expat
    - lz4-c
    - bzip2
    - zlib
    - nlohmann_json

  run:
    - lz4-c
    - bzip2
    - libzlib


test:
  commands:
    - test -f $PREFIX/bin/osmium                                # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\osmium.exe exit 1     # [win]


about:
  home: https://osmcode.org/osmium-tool/
  license: GPL-3.0-only
  license_file:
    - osmium-tool/LICENSE.txt
    - libosmium/LICENSE
    - protozero/LICENSE.md
  summary: Osmium Command Line Tool.
  description: |
    Osmium is a versatile command line tool for working with OpenStreetMap data.
    It includes many useful functions for manipulating OSM data, e.g. get
    information about an OSM file, show the differences between OSM files, convert
    OSM files from one format into another, merge and apply change files to an OSM
    file, create geographical extracts from OSM files, filter OSM files by tags,
    and much more...
  doc_url: https://osmcode.org/osmium-tool/manual.html
  dev_url: https://github.com/osmcode/osmium-tool


extra:
  recipe-maintainers:
    - OliverSchmitz
    - kordejong
